# Core
db:
  redis:
    host: redis-17830.c44.us-east-1-2.ec2.cloud.redislabs.com
    port: 17830
    password: B1GsZOjEAiimRg2Z1xfu8s4qYuSv1QX2
    namespace: EG

#plugins:
  # express-gateway-plugin-example:
  #   param1: 'param from system.config' 

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000
